### ISSUE TITLE
Atom: trying to install 0.3.0 while 0.2.1 is the only one available

### ISSUE THREAD

**Issue by martijnvankekem** [Samsung/atom-tizentv#1]

**Comment by sutaking** [comment]
Hi,
The newest version of atom-tizentv is 0.2.1 now, and all features are available.
sorry to be confused by the version number

**Comment by martijnvankekem** [comment]
It's not that I'm confused, it's that the package manager of Atom tries to install version 0.3.0, while this version doesn't exist. Atom should try to install 0.2.1, but it doesn't.

**Comment by sutaking** [comment]
Hi, We already update version to 0.3.1
